//! The shared vocabulary for the syren: the autogenerated syscall
//! table ([`SYSCALLS`]) and the core event types ([`Event`], [`SyscallEvent`])
//! that flow from the tracing backends through decoding and into the output
//! formatters.
//!
//! The syscall table itself is generated at build time by `syren-gen` from the
//! vendored `data/syscall_64.tbl`.

mod errno;
mod event;

pub use errno::{Errno, errno};
pub use event::{Event, SyscallEvent};
use serde::{Deserialize, Serialize};

/// Coarse syscall category.
/// Kept variant-for-variant in sync with `syren_gen::Category`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Category {
    /// Filesystem & file-descriptor I/O.
    Fs,
    /// Networking / sockets.
    Net,
    /// Memory management.
    Memory,
    /// Process & thread lifecycle.
    Process,
    /// Signal handling.
    Signal,
    /// Inter-process communication & synchronisation.
    Ipc,
    /// Time & timers.
    Time,
    /// Security, credentials & capabilities.
    Security,
    /// Generic system / kernel control.
    System,
    /// Anything not otherwise classified.
    Other,
}

impl Category {
    /// All categories, for iteration in the CLI and aggregations.
    pub const ALL: [Category; 10] = [
        Category::Fs,
        Category::Net,
        Category::Memory,
        Category::Process,
        Category::Signal,
        Category::Ipc,
        Category::Time,
        Category::Security,
        Category::System,
        Category::Other,
    ];

    /// Lowercase, stable name used in CLI flags and JSON.
    pub fn as_str(self) -> &'static str {
        match self {
            Category::Fs => "fs",
            Category::Net => "net",
            Category::Memory => "memory",
            Category::Process => "process",
            Category::Signal => "signal",
            Category::Ipc => "ipc",
            Category::Time => "time",
            Category::Security => "security",
            Category::System => "system",
            Category::Other => "other",
        }
    }

    /// Parse a category from its lowercase name (case-insensitive).
    pub fn parse(s: &str) -> Option<Category> {
        Category::ALL.into_iter().find(|c| c.as_str().eq_ignore_ascii_case(s))
    }
}

/// The display/decoding kind of a single argument.
/// How a single syscall argument should be decoded and rendered.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ArgType {
    /// A file descriptor (`int`). Rendered as a decimal, annotated with the
    /// resolved path when known.
    Fd,
    /// A `const char *` pathname. Rendered as a quoted string.
    Path,
    /// A `void *` data buffer. Rendered as a pointer (content capture is opt-in).
    Buf,
    /// A `size_t` / count. Rendered as a decimal.
    Size,
    /// A signed integer.
    Int,
    /// An unsigned integer.
    Uint,
    /// An opaque value best shown in hex (`ioctl` request, `fcntl` arg, ...).
    Hex,
    /// An `off_t` file offset.
    Offset,
    /// A bit-flag set (`open` flags, `mmap` prot, ...). Rendered in hex for now,
    /// with symbolic decoding layered on top in `syren-decode`.
    Flags,
    /// A generic pointer (structs we do not yet decode).
    Ptr,
}

/// A single argument of a syscall: name plus decoding type.
#[derive(Debug, Clone, Copy)]
pub struct ArgInfo {
    /// Argument name as it appears in the man page.
    pub name: &'static str,
    /// How to decode/render this argument.
    pub ty: ArgType,
}

/// Static description of a syscall: number, name, category and (for the hot
/// syscalls) typed argument metadata.
#[derive(Debug, Clone, Copy)]
pub struct SyscallInfo {
    /// Syscall number on the x86_64 ABI.
    pub number: u32,
    /// Syscall name (e.g. `openat`).
    pub name: &'static str,
    /// Coarse category.
    pub category: Category,
    /// Typed arguments, or an empty slice when no metadata is available.
    pub args: &'static [ArgInfo],
}

// Bring in the generated `SYSCALLS` table and `SYSCALL_COUNT`.
mod generated {
    include!(concat!(env!("OUT_DIR"), "/syscalls_generated.rs"));
}
pub use generated::{SYSCALL_COUNT, SYSCALLS};

/// Look up a syscall by its number. `O(log n)` — the table is sorted.
pub fn syscall_by_number(number: u32) -> Option<&'static SyscallInfo> {
    SYSCALLS.binary_search_by_key(&number, |s| s.number).ok().map(|i| &SYSCALLS[i])
}

/// Look up a syscall by name.
pub fn syscall_by_name(name: &str) -> Option<&'static SyscallInfo> {
    SYSCALLS.iter().find(|s| s.name == name)
}

/// The display name for a raw syscall number.
pub fn syscall_name(nr: u64) -> std::borrow::Cow<'static, str> {
    match u32::try_from(nr).ok().and_then(syscall_by_number) {
        Some(info) => std::borrow::Cow::Borrowed(info.name),
        None => std::borrow::Cow::Owned(format!("syscall_{nr}")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_is_populated_and_sorted() {
        assert_eq!(SYSCALLS.len(), SYSCALL_COUNT);
        assert!(SYSCALLS.len() >= 300, "expected full x86_64 table, got {}", SYSCALLS.len());
        assert!(SYSCALLS.windows(2).all(|w| w[0].number < w[1].number));
    }

    #[test]
    fn canonical_numbers_correct() {
        assert_eq!(syscall_by_name("read").unwrap().number, 0);
        assert_eq!(syscall_by_name("write").unwrap().number, 1);
        assert_eq!(syscall_by_name("open").unwrap().number, 2);
        assert_eq!(syscall_by_name("close").unwrap().number, 3);
        assert_eq!(syscall_by_name("mmap").unwrap().number, 9);
        assert_eq!(syscall_by_name("execve").unwrap().number, 59);
        assert_eq!(syscall_by_name("exit").unwrap().number, 60);
        assert_eq!(syscall_by_name("openat").unwrap().number, 257);
    }

    #[test]
    fn lookup_round_trips() {
        for s in SYSCALLS {
            assert_eq!(syscall_by_number(s.number).unwrap().name, s.name);
        }
    }

    #[test]
    fn categories_are_assigned() {
        assert_eq!(syscall_by_name("openat").unwrap().category, Category::Fs);
        assert_eq!(syscall_by_name("connect").unwrap().category, Category::Net);
        assert_eq!(syscall_by_name("mmap").unwrap().category, Category::Memory);
    }

    #[test]
    fn typed_args_present_for_hot_syscalls() {
        let read = syscall_by_name("read").unwrap();
        assert_eq!(read.args.len(), 3);
        assert_eq!(read.args[0].ty, ArgType::Fd);
    }

    #[test]
    fn unknown_number_placeholder() {
        assert_eq!(syscall_name(999_999), "syscall_999999");
        assert_eq!(syscall_name(0), "read");
    }

    #[test]
    fn category_parse_round_trips() {
        for c in Category::ALL {
            assert_eq!(Category::parse(c.as_str()), Some(c));
        }
        assert_eq!(Category::parse("NET"), Some(Category::Net));
        assert_eq!(Category::parse("nonsense"), None);
    }
}
