//! Emits the `SYSCALLS` table as Rust source.
//!
//! The generated file is `include!`d by `syren-common`, so it refers to the
//! public types defined there (`crate::SyscallInfo`, `crate::Category`,
//! `crate::ArgInfo`, `crate::ArgType`).

use std::fmt::Write as _;

use crate::category::categorize;
use crate::meta;
use crate::table::parse_tbl;

/// Generate the contents of the `syscalls_generated.rs` file from the raw
/// `syscall_64.tbl` text.
pub fn generate(tbl: &str) -> String {
    let entries = parse_tbl(tbl);

    let mut out = String::with_capacity(64 * 1024);
    out.push_str(
        "// @generated by syren-gen — DO NOT EDIT.\n\
         // Regenerated from crates/syren-common/data/syscall_64.tbl at build time.\n\n",
    );

    let _ = writeln!(out, "/// Number of syscalls known to syren on this ABI.");
    let _ = writeln!(out, "pub const SYSCALL_COUNT: usize = {};\n", entries.len());

    out.push_str("/// All known syscalls, sorted by syscall number.\n");
    out.push_str("pub static SYSCALLS: &[crate::SyscallInfo] = &[\n");
    for e in &entries {
        let category = categorize(&e.name);
        let args = render_args(&e.name);
        let _ = writeln!(
            out,
            "    crate::SyscallInfo {{ number: {n}, name: {name:?}, \
             category: crate::Category::{cat}, args: {args} }},",
            n = e.number,
            name = e.name,
            cat = category.ident(),
            args = args,
        );
    }
    out.push_str("];\n");
    out
}

fn render_args(name: &str) -> String {
    match meta::lookup(name) {
        None => "&[]".to_string(),
        Some(m) if m.args.is_empty() => "&[]".to_string(),
        Some(m) => {
            let mut s = String::from("&[");
            for (i, arg) in m.args.iter().enumerate() {
                if i > 0 {
                    s.push_str(", ");
                }
                let _ = write!(
                    s,
                    "crate::ArgInfo {{ name: {name:?}, ty: crate::ArgType::{ty} }}",
                    name = arg.name,
                    ty = arg.kind,
                );
            }
            s.push(']');
            s
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TBL: &str = "\
0\tcommon\tread\t\t\tsys_read
2\tcommon\topen\t\t\tsys_open
39\tcommon\tgetpid\t\t\tsys_getpid
9\tcommon\tmmap\t\t\tsys_mmap
999\tcommon\tnodecode_syscall\tsys_nodecode
";

    #[test]
    fn emits_count_and_entries() {
        let src = generate(TBL);
        assert!(src.contains("pub const SYSCALL_COUNT: usize = 5;"));
        assert!(src.contains("number: 0, name: \"read\""));
        assert!(src.contains("crate::Category::Fs"));
        assert!(src.contains("crate::Category::Memory"));
    }

    #[test]
    fn known_syscall_gets_typed_args() {
        let src = generate(TBL);
        assert!(src.contains("crate::ArgInfo { name: \"fd\", ty: crate::ArgType::Fd }"));
        assert!(src.contains("crate::ArgType::Size"));
    }

    #[test]
    fn unknown_syscalls_empty_args() {
        let src = generate(TBL);
        assert!(src.contains("name: \"getpid\", category: crate::Category::Process, args: &[]"));
        assert!(src.contains("name: \"nodecode_syscall\""));
        assert!(src.contains("args: &[]"));
    }

    #[test]
    fn output_is_sorted_by_number() {
        let src = generate(TBL);
        let read_at = src.find("name: \"read\"").unwrap();
        let mmap_at = src.find("name: \"mmap\"").unwrap();
        let getpid_at = src.find("name: \"getpid\"").unwrap();
        assert!(read_at < mmap_at && mmap_at < getpid_at);
    }
}
